#!/bin/bash -eu

IN="$(cat)"

listing() {

	# strip
	local S="$(grep "^[a-z]" <<<"$IN")"

	# list of characters
	local C="$(cut -d " " -f 2- <<<"$S")"

	# list of canjie codes
	local E="$(cut -d " " -f 1 <<<"$S")"

	# one character per line
	local N="$(wc -l <<<"$C")"
	[ "$(wc -m <<<"$C")" = "$((N*2))" ]

	# list of utf-16 of each character
	local A=($(echo "$C" | sed "s/^/'/g"))
	local U="$(printf "%d\n" "${A[@]}")"
	[ "$(wc -l <<<"$U")" = "$N" ]

	# listing
	paste -d " " <(echo "$U") <(echo "$E") | sort -s -n

}

unique() {
	local i=0
	local T=()
	set +u
	local l
	while read -r l; do
		#if ((0==(i++)%10000)); then echo "$i"; fi
		local L=($l)
		[ 2 = "${#L[@]}" ]
		local k="${L[0]}"
		local v="${L[1]}"
		T["$k"]="${T["$k"]} $v"
	done
	set -u
	for i in "${!T[@]}"; do
	  printf "%s%s\n" "$i" "${T["$i"]}"
	done
}


generate() {
	local l
	printf "Entry T[] = {\n"
	while read -r l; do
		local L=($l)
		printf "\t[%s] = { .n = %s, .e=(const char *[]){" "${L[0]}" "$(("${#L[@]}"-1))"
		printf '"%s", ' "${L[@]:1}"
		printf "nullptr} },\n"
	done
	printf "\t[0] = {}\n"
	printf "};\n"
}

#tee table.c <<EOF
cat >table.c <<EOF

// generated by gen.sh

// do not modify

#include <stddef.h>
#include "table.h"

$(listing | unique | generate)

EOF

